// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_pack
RawVector c_pack(SEXP root_obj);
RcppExport SEXP _msgpack2R_c_pack(SEXP root_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type root_obj(root_objSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pack(root_obj));
    return rcpp_result_gen;
END_RCPP
}
// c_unpack
SEXP c_unpack(std::vector<unsigned char> char_message);
RcppExport SEXP _msgpack2R_c_unpack(SEXP char_messageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<unsigned char> >::type char_message(char_messageSEXP);
    rcpp_result_gen = Rcpp::wrap(c_unpack(char_message));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msgpack2R_c_pack", (DL_FUNC) &_msgpack2R_c_pack, 1},
    {"_msgpack2R_c_unpack", (DL_FUNC) &_msgpack2R_c_unpack, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_msgpack2R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
