# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_pack <- function(root_obj) {
    .Call('_msgpack2R_c_pack', PACKAGE = 'msgpack2R', root_obj)
}

c_unpack <- function(char_message) {
    .Call('_msgpack2R_c_unpack', PACKAGE = 'msgpack2R', char_message)
}

